name: hamo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  salomon_bottom_bar: 3.3.1
  cached_network_image: 3.2.2
  shimmer: 2.0.0
  flutter: 
    sdk: flutter
  shared_preferences: ^2.0.15
  fluttertoast: ^8.1.1
  readmore: ^2.2.0
  intl: ^0.17.0
  syncfusion_flutter_datepicker: ^20.3.58
  expandable: ^5.0.1
  image_picker: ^0.8.6
  dio: ^4.0.6
  flutter_rating_bar: ^4.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

